In [1]:
import numpy as np

In [2]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [5]:
arr / arr

C:\Users\Amr Ahmed\AppData\Local\Temp\ipykernel_12488\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [6]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [8]:
arr * 100

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [9]:
1/0

ZeroDivisionError: division by zero

In [10]:
1 / arr

C:\Users\Amr Ahmed\AppData\Local\Temp\ipykernel_12488\1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [11]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

---------------- Universal Functions ----------------

In [12]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [13]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [14]:
np.max(arr)

9

In [16]:
arr.max()

9

In [15]:
np.min(arr)

0

In [17]:
arr.min()

0

In [18]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [19]:
np.log(arr)

np.log10(arr)

np.log2(arr)

np.sinh(arr)

np.cosh(arr)

np.tanh(arr)

np.arcsin(arr)

np.arccos(arr)

np.arctan(arr)

np.deg2rad(arr)

np.rad2deg(arr)

C:\Users\Amr Ahmed\AppData\Local\Temp\ipykernel_12488\8361567.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)
C:\Users\Amr Ahmed\AppData\Local\Temp\ipykernel_12488\8361567.py:3: RuntimeWarning: divide by zero encountered in log10
  np.log10(arr)
C:\Users\Amr Ahmed\AppData\Local\Temp\ipykernel_12488\8361567.py:5: RuntimeWarning: divide by zero encountered in log2
  np.log2(arr)
C:\Users\Amr Ahmed\AppData\Local\Temp\ipykernel_12488\8361567.py:13: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(arr)
C:\Users\Amr Ahmed\AppData\Local\Temp\ipykernel_12488\8361567.py:15: RuntimeWarning: invalid value encountered in arccos
  np.arccos(arr)


array([  0.        ,  57.29577951, 114.59155903, 171.88733854,
       229.18311805, 286.47889757, 343.77467708, 401.07045659,
       458.3662361 , 515.66201562])