In [1]:
import numpy as np

In [2]:
myList = [1,2,3]
myList

[1, 2, 3]

In [39]:
array = np.array(myList)
array

array([1, 2, 3])

In [9]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(4)

array([0., 0., 0., 0.])

In [16]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones(3)

array([1., 1., 1.])

In [21]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [25]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
np.random.rand(5)   # rand => Values between 0 and 1

array([0.51909388, 0.18887999, 0.14949953, 0.03802633, 0.92285868])

In [28]:
np.random.rand(5,5) # Gaussian distribution

array([[0.49913564, 0.95327429, 0.77160904, 0.69030517, 0.43839488],
       [0.07020073, 0.62034155, 0.38582619, 0.08731441, 0.39819949],
       [0.1421369 , 0.65937349, 0.99206299, 0.82807158, 0.28517173],
       [0.43502605, 0.14240097, 0.2297338 , 0.0013203 , 0.63638132],
       [0.63408476, 0.06546704, 0.07473515, 0.13868753, 0.38572045]])

In [30]:
np.random.randn(5) # Normal distribution

array([-1.9916002 , -1.22124653, -1.38312348,  1.8253487 , -2.57389965])

In [37]:
np.random.randn(5,5)

array([[-1.24550016, -0.80345036,  1.11321707, -0.44146965, -1.57012653],
       [-0.30626885,  0.50206155, -0.97831407,  0.06552581, -1.44826318],
       [-0.77767373, -1.44541762,  0.24735455, -0.54261877,  0.46564339],
       [-1.63402678,  0.81975813,  0.28134778, -1.41612784, -1.21169573],
       [-0.49618417,  1.85363113,  0.42922213,  0.43429159,  0.32319849]])

In [34]:
np.random.randint(1,100)

59

In [35]:
np.random.randint(1,100,10) # 10 random numbers

array([26, 13, 77, 92, 51, 32, 69, 80, 98, 80])

In [40]:
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
ranarr = np.random.randint(0,50,10)
ranarr

array([ 7, 19, 21, 38, 46,  1, 25, 38, 32, 34])

In [46]:
arr.shape

(25,)

In [43]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [54]:
arr.dtype

dtype('int32')

In [52]:
ranarr

array([ 7, 19, 21, 38, 46,  1, 25, 38, 32, 34])

In [47]:
ranarr.max()

46

In [48]:
ranarr.min()

1

In [51]:
ranarr.argmax()

4

In [53]:
ranarr.argmin()

5