In [3]:
import pandas as pd
import numpy as np

In [9]:
np.random.seed(101)
df = pd.DataFrame(np.random.randn(6, 4), index=list('abcdef'), columns=list('WXYZ'))
df

W         X         Y         Z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509
f  0.302665  1.693723 -1.706086 -1.159119

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, a to f
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   W       6 non-null      float64
 1   X       6 non-null      float64
 2   Y       6 non-null      float64
 3   Z       6 non-null      float64
dtypes: float64(4)
memory usage: 240.0+ bytes


In [11]:
df.describe()

W         X         Y         Z
count  6.000000  6.000000  6.000000  6.000000
mean   0.336992  0.660424  0.092558  0.166706
std    1.503744  1.075862  1.571280  0.839534
min   -2.018168 -0.758872 -1.706086 -1.159119
25%    0.189220 -0.082455 -0.911947 -0.315794
50%    0.246730  0.684127 -0.159632  0.554896
75%    0.564005  1.455323  0.813180  0.664123
max    2.706850  1.978757  2.605967  0.955057

In [14]:
df.head(3)

W         X         Y         Z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001

In [15]:
df[:4]

W         X         Y         Z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057

In [17]:
df.tail(2)

W         X         Y         Z
e  0.190794  1.978757  2.605967  0.683509
f  0.302665  1.693723 -1.706086 -1.159119

In [20]:
df.columns

Index(['W', 'X', 'Y', 'Z'], dtype='object')

In [22]:
df.index

Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='object')

In [23]:
df.shape

(6, 4)

In [24]:
df.dtypes

W    float64
X    float64
Y    float64
Z    float64
dtype: object

In [25]:
df.count()

W    6
X    6
Y    6
Z    6
dtype: int64

In [27]:
df.values

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889],
       [ 0.30266545,  1.69372293, -1.70608593, -1.15911942]])

In [28]:
df.to_numpy()

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889],
       [ 0.30266545,  1.69372293, -1.70608593, -1.15911942]])

In [29]:
s = pd.Series([1,2,3,4],['A','B','C','D'])
s

A    1
B    2
C    3
D    4
dtype: int64

In [30]:
s.describe()

count    4.000000
mean     2.500000
std      1.290994
min      1.000000
25%      1.750000
50%      2.500000
75%      3.250000
max      4.000000
dtype: float64

In [31]:
s.values

array([1, 2, 3, 4], dtype=int64)

In [33]:
s.value_counts()

1    1
2    1
3    1
4    1
Name: count, dtype: int64

In [35]:
s.shape

(4,)

In [36]:
s.index

Index(['A', 'B', 'C', 'D'], dtype='object')

In [37]:
s.unique()

array([1, 2, 3, 4], dtype=int64)

In [38]:
s.nunique()

4

In [40]:
s.apply(lambda x: x**2)

A     1
B     4
C     9
D    16
dtype: int64