# Creating NumPy Arrays

## Import NumPy Module

In [27]:
import numpy as np

### Creating 1D NumPy Array

In [28]:
a = np.array([1,2,3])
a

### Creating 2D NumPy Array

In [38]:
b = np.array([[1.5,2,3],[4,5,6]], dtype = float)
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

### Initial NumPy Array Placeholders

In [31]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [33]:
arr = np.arange(0,11,2)
arr

array([ 0,  2,  4,  6,  8, 10])

In [34]:
arr = np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
arr = np.ones((4,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
arr = np.linspace(1,2,9)
arr

array([1.   , 1.125, 1.25 , 1.375, 1.5  , 1.625, 1.75 , 1.875, 2.   ])

In [37]:
arr = np.random.randint(20,50,10)
arr

array([27, 30, 49, 32, 30, 27, 38, 28, 45, 29])

# Inspecting Numpy Arrays

In [43]:
a.shape

(3,)

In [48]:
a.ndim

1

In [50]:
b.size

6

In [52]:
b.dtype.name

'float64'

In [57]:
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

# Subsetting, Slicing, & Indexing

## Indexing / Subsetting

In [106]:
a

array([1, 2, 3])

In [107]:
a[1]

2

In [108]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [109]:
b[1,1]

5.0

## Slicing

In [110]:
a[0:2]

array([1, 2])

In [111]:
b[:, 0:2]

array([[1.5, 2. ],
       [4. , 5. ]])

In [114]:
b[:1]

array([[1.5, 2. , 3. ]])

## Boolean Indexing

In [120]:
a[a < 3]

array([1, 2])

# Manipulating NumPy Arrays

In [84]:
np.insert(a,1,5)

array([1, 5, 2, 3])

In [97]:
a

array([1, 2, 3])

In [99]:
np.delete(a,1)

array([1, 3])

In [101]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [103]:
b.reshape(3,2)

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

In [105]:
np.append(a,b)

array([1. , 2. , 3. , 1.5, 2. , 3. , 4. , 5. , 6. ])

# NumPy Array Mathematics

## NumPy Arithmetic Operations

In [122]:
a

array([1, 2, 3])

In [123]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [124]:
b + a

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [125]:
np.add(b,a)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [126]:
np.subtract(b,a)

array([[0.5, 0. , 0. ],
       [3. , 3. , 3. ]])

In [127]:
np.multiply(a,b)

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [128]:
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [129]:
np.sin(b)

array([[ 0.99749499,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [131]:
np.log(b)

array([[0.40546511, 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

## NumPy Statistical Operations

In [132]:
a

array([1, 2, 3])

In [133]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [134]:
a.sum()

6

In [135]:
b.min()

1.5

In [136]:
b.max()

6.0

In [137]:
b.mean()

3.5833333333333335

In [139]:
np.median(b)

3.5

In [140]:
np.std(b)

1.5920810978785667

In [141]:
b.std()

1.5920810978785667