In [1]:
import numpy as np

###     Creating Array

#### Most used functions to create array
- array()
- random.rand()
- random.randint()
- linspace() 
- arange()

In [8]:
a = np.array(40)   
a 

array(40)

In [9]:
b = np.array([1,2,3,4])
b

array([1, 2, 3, 4])

In [6]:
c= np.array([[1,2,3],[3,4,5]])
c

array([[1, 2, 3],
       [3, 4, 5]])

In [7]:
d = np.array([[[1,2],[3,4],[5,6]]])
d

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.full((2,3),8)

array([[8, 8, 8],
       [8, 8, 8]])

In [24]:
np.empty((2,2)) #garbage value from memory

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 9.01848211e-312]])

In [25]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(4,10,2) # 4 to 9 with 2 increments  

array([4, 6, 8])

In [29]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [30]:
np.linspace(0,10,5) # 0 to 10 with 5 intervals

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [46]:
np.arange(0,10,5)

array([0, 5])

In [36]:
np.random.rand(3,2)

array([[0.39243275, 0.60669027],
       [0.24781677, 0.3163589 ],
       [0.3911735 , 0.92168825]])

In [38]:
np.random.randint(4,10,size=(4,5))

array([[7, 5, 9, 6, 8],
       [9, 6, 5, 6, 9],
       [5, 4, 9, 7, 7],
       [7, 5, 6, 4, 5]])

In [39]:
np.random.normal(5,2,3) #mean 5 and standard deviation 2, 3 dimensions

array([3.76811525, 2.23967195, 5.180401  ])

In [40]:
np.random.randn(6)  

array([ 1.01945346,  0.43377926,  1.28783979, -0.32181504, -0.16429452,
        0.72457774])

In [43]:
d

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [41]:
np.zeros_like(d)

array([[[0, 0],
        [0, 0],
        [0, 0]]])

In [42]:
np.ones_like(d)

array([[[1, 1],
        [1, 1],
        [1, 1]]])

#### Inspecting Properties

In [10]:
c

array([[1, 2, 3],
       [3, 4, 5]])

In [11]:
c.ndim

2

In [12]:
c.shape

(2, 3)

In [13]:
c.size

6

In [14]:
b.shape

(4,)

In [15]:
b.size

4

In [16]:
d

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [20]:
d.shape

(1, 3, 2)

In [22]:
c.dtype

dtype('int32')

In [26]:
c.astype(np.float64).dtype

dtype('float64')

#### Data Type

In [30]:
pop = np.array([7000000000],dtype=np.int64)
pop

array([7000000000], dtype=int64)

#### Indexing and slicing

In [31]:
a = np.array([1,2,3,4])

In [32]:
a[1]

2

In [33]:
a[-1]

4

In [34]:
a[3]

4

In [37]:
a[1:3]

array([2, 3])

In [44]:
a[:]    #selects all elements


array([1, 2, 3, 4])

In [42]:
b = np.arange(6).reshape(3,2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [43]:
b[1,1]  #equivalent to b[1][1]

3

In [46]:
b[ : , : ]  #selects all elements

array([[0, 1],
       [2, 3],
       [4, 5]])

In [47]:
b[0 , :]

array([0, 1])

In [48]:
b[1: , 0:]

array([[2, 3],
       [4, 5]])

In [52]:
b[ : :2 , :] #selects all elements with step 2

array([[0, 1],
       [4, 5]])

In [59]:
b[[0,2] ,:] #selects all elements with index 0 and 2
# fancy indexing

array([[0, 1],
       [4, 5]])

In [61]:
b[ [0,1] , [1] ]    #fancy indexing

array([1, 3])

In [53]:
b[ 0:3:2 , 0:2] #selects all elements with step 2

array([[0, 1],
       [4, 5]])

##### Boolean Indexing

In [55]:
b < 3

array([[ True,  True],
       [ True, False],
       [False, False]])

In [56]:
b[b<3]  #selects all elements less than 3

array([0, 1, 2])

##### Example

In [4]:
arr = np.arange(25).reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [65]:
# Get Last row
arr[-1]

array([20, 21, 22, 23, 24])

In [67]:
# Get all rows and last column
arr[:, -1]

array([ 4,  9, 14, 19, 24])

In [5]:
arr[ : , [1,3] ]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

#### Adding & Removing Elements

In [28]:
b = np.array([1,2,3,4])

In [29]:
b = np.append(b,7)

In [30]:
b

array([1, 2, 3, 4, 7])

In [32]:
b = np.insert(b, 2, 10)
b

array([ 1,  2, 10, 10,  3,  4,  7])

In [33]:
b = np.delete(b, -1)
b

array([ 1,  2, 10, 10,  3,  4])

In [34]:
b

array([ 1,  2, 10, 10,  3,  4])

In [43]:
b[:] = 0
b

array([0, 0, 0, 0, 0, 0])

#### Combine and Split

In [3]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [11]:
# Concatenate arr1 and arr2
arr3 = np.concatenate((arr1,arr2))
arr3

array([1, 2, 3, 4, 5, 6])

In [12]:
d = np.vstack((arr1,arr2))
d

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
e = np.hstack((arr1,arr2)) 
e

array([1, 2, 3, 4, 5, 6])

In [18]:
# split arr array into two parts
x,y = np.split(arr3,2)

In [19]:
x

array([1, 2, 3])

In [20]:
y

array([4, 5, 6])

In [21]:
# split arr array into three parts horizontally
x,y,z = np.hsplit(arr3,3)
#print x,y,z
print({'x':x,'y':y,'z':z})

{'x': array([1, 2]), 'y': array([3, 4]), 'z': array([5, 6])}


#### Copy , Sort and Reshape

In [26]:
arr1

array([1, 2, 3])

In [27]:
arr2

array([4, 5, 6])

In [29]:
# sort arr1 in reverse order
np.sort(arr1)[::-1]


array([3, 2, 1])

In [31]:
arr1.dtype

dtype('int32')

#### Math and statistics

In [38]:
d

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
# Mean of each column
np.mean(d,axis=0)

# Mean of each row
np.mean(d,axis=1)

array([2., 5.])